### ISSUE TITLE
Document aliases

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2book#173]
See `$?` command output.

**Comment by XVilka** [comment]
Note that some aliases we documented in various radare2 talks.

**Comment by officialcjunior** [comment]
Where do you think we should add information about them?

**Comment by Maijin** [comment]
New chapter in scripting https://github.com/radareorg/radare2book/tree/master/src/scripting like macros

**Comment by officialcjunior** [comment]
Is there anything more to be added related to this issue?
If not, I think we can close this.
