### ISSUE TITLE
How to insert an assembly instruction

### ISSUE THREAD

**Issue by shijiameng** [radareorg/radare2book#228]
I am going to patch an ARM ELF file by inserting assembler instructions. For example, in the following codes

   15a1a:       2000            movs    r0, #0
   15a1c:       4798            blx     r3

If I wanted to insert an instruction "ldr r3, [r3, #0]" between 0x15a1a and 0x15a1c and make it like this:

   15a1a:       2000            movs    r0, #0
   15a1c:        xxxx            ldr     r3, [r3, #0]  // shift the following instruction, rather than overwriting
   15a1e:       4798            blx     r3

What should I do?

**Comment by officialcjunior** [comment]
Did you try:

`wx 003093e5 @ 0x15a1c`

---
I mean,
`wx <opcode> @ <memory_address>`

Alse, see the section write in basic commands.

**Comment by ITAYC0HEN** [comment]
Thanks for the question :) And thanks to @officialcjunior for the answer <3

It is recommended to ask questions about radare2 in the official chats (Telegram, IRC) - you'll get a fast reply.

Thanks again!
