### ISSUE TITLE
Restructure dietline chapter or create a new one

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2book#270]
To organize the list of the hotkeys like in this guide:

[Emacs mode](https://readline.kablamo.org/emacs.html):

![image](https://user-images.githubusercontent.com/203261/91278239-86366f80-e7b6-11ea-8008-7c0633dbc052.png)

[Vi mode](https://readline.kablamo.org/vi.html):

![image](https://user-images.githubusercontent.com/203261/91278564-f6dd8c00-e7b6-11ea-903d-8da03a61f748.png)

**Comment by officialcjunior** [comment]
Would just adding the respective titles and grouping them together be enough?
