### ISSUE TITLE
Dead link on the documentation

### ISSUE THREAD

**Issue by SakiiR** [radareorg/radare2book#276]
The second link of the page [https://radare.gitbooks.io/radare2book/content/crackmes/ioli/intro.html](https://radare.gitbooks.io/radare2book/content/crackmes/ioli/intro.html) is dead (https://github.com/radareorg/radare2book/tree/master/crackmes/ioli/IOLI-crackme.tar.gz).

Just a brief report .

**Comment by officialcjunior** [comment]
I think we can link that to (https://github.com/radareorg/radare2-testbins/tree/master/elf/ioli), instead.

**Comment by wargio** [comment]
Fixed by https://github.com/radareorg/radare2book/commit/8f06f07bb7544193a50f5db0d7bad107a3a41601
