### ISSUE TITLE
This phrase make no sense (or I'm missing something)

### ISSUE THREAD

**Issue by tomasz-rozanski** [radareorg/radare2book#294]
In the `/src/first_steps/history.md` there is a phrase:
```
Since he wasn't allowed to use private software for his personal needs, he decided to write a small tool (...)
```
So, he wrote another piece of software which he couldn't use, or do you mean, that he wasn't allowed to use the software from his workplace for personal projects?

**Comment by wargio** [comment]
@trufae this is yours!

**Comment by trufae** [comment]
yep the 2nd

**Comment by wargio** [comment]
I'll close this, then.

**Comment by wargio** [comment]
ah @tomasz-rozanski feel free to fix the english sentence with a PR if you think is necessary to understand the meaning of it.
